### ISSUE TITLE
Web app deploy 

### ISSUE THREAD

**Issue by houdamzari** [Lucas-Erkana/math_magician_react#10]
Hey @Lucash2022 , you have done some great work, 
Kindly check the deployed link because it gets broken once you refresh the homepage. 

 [](url)
![Site-not-found-·-GitHub-Pages](https://user-images.githubusercontent.com/73146419/212618317-4130be64-e570-442e-93cf-decad2414174.png)

**Comment by Lucas-Erkana** [comment]
- Fix the load Home page first at this [link](https://github.com/Lucash2022/math_magician_react/blob/8ec065ba02ef26b6800f5dc38a64f6af542865da/src/App.js#L13)
- To load the home page immediately, I need to specify the default path of the router. To do this, I added basename={process.env.PUBLIC_URL} to the <Router> component.
- What I did above fixed the refresh once am on the home page, But as soon as I go to the Calculator and Quote and refresh the error comes up again. Let me fix that later
